# Basic flag to wait for the parameters to be loaded in.
params_loaded: True

# The parameter for executing navigation commands. This doesn't stop manipulation from navigating, but 
# it will stop TLP from doing so. Very useful for debugging, and the state machines will fail to run if
# this is not run.
execute_navigation_commands: true


# Flag now built into manipulation run_all.py. Allows for the dynamic toggling of gpg and collision mapping.
use_grasping_synthesis: false
use_collision_mapping: false

# For putting down objects next to others
find_placement_options : {
    # Looks for a plane height meters below the point given. This should thus probably be like 20cm max.
    height : 0.2,
    # Looks for placement options radius away
    radius : 0.1,
    # Assumes the object is dims in dimension.
    dims : [0.05, 0.05, 0.02]
}

# The poses the robot will navigate to for doing stuff.
table_pose : {
    # Bordeaux
    # position : {
    #     x: 6.898829284925901, y: -0.3345450406571554, z: 0.0
    # },
    # orientation : { 
    #     x: 0.0, y: 0.0, z: 0.9941701850029624, w: 0.1078222762288735
    # }
    # Simulation
    position : {
        x : 4.61, y : 0.308, z : 0
    },
    orientation : {
        x : 0, y : 0, z : 0.751, w : 0.66
    }
}
cabinet_pose : {
    # Bordeaux
    # position : {
    #     x: 6.921234442581973, y: -0.28322414645887983, z: 0.0
    # },
    # orientation : { 
    #     x: 0.0, y: 0.0, z: 0.5969085861979543, w: 0.8023092544169981
    # }
    # Simulation
    position : {
        x : 2.62, y : 0.36, z : 0
    },
    orientation : {
        x : 0, y : 0, z : -0.821, w : 0.571
    }
}

# This list is in order of priority. If it sees a drink, it will try 
# to pick this up first. Then fruits. etc. "tableware" is hard, so 
# that's close to the bottom. We will not attempt containers or cutlery.
categories_to_pick_up : [
    "fruits", 
    "drinks", 
    "food", 
    "snacks", 
    "tableware", 
    "cleaning_stuff"]

# There will be false positives within the vision system. However, we will count ourselves very unlucky if
# we get multiple false positives of the same field. Thus, when we query into the SOM system, we will be 
# looking for a minimum number of observations, given below. On the SOM side, this is input by simply setting
# the `num_observations` parameter within the query.
min_number_of_observations : 3

# The height that the robot mast goes to upon arriving at the table etc.
table_mast_height : 0
cabinet_mast_height : 0


# Next thing to worry about is potentially hardcoding the shelves.
# These are added as an rviz visual under the address "zzz_task_level_planning/markers" 
# It then looks for the highest shelf that is below a given object and then assumes that that is the shelf
# the object is sitting on. Thus the shelf heights should ideally be under-estimates rather than over-estimates. 
# width and depth are then the width and depth of the shelves.
use_hardcoded_shelves : true
shelves_hardcoded : {
    normal: [0,0,1],
    z_vals: [0.2,0.5,1,1.5],
    # Pose of the base of the shelves
    shelf_pose: {
        position : {
            x : 2.62, y : 0.36, z : 0
        },
        orientation : {
            x : 0, y : 0, z : -0.821, w : 0.571
        }
    },
    width : 0.5,
    depth : 0.2
}