# Basic flag to wait for the parameters to be loaded in.
params_loaded: True

execute_navigation_commands: true

# For putting down objects next to others
find_placement_options : {
    # Looks for a plane height meters below the point given. This should thus probably be like 20cm max.
    height : 0.2,
    # Looks for placement options radius away
    radius : 0.1,
    # Assumes the object is dims in dimension.
    dims : [0.05, 0.05, 0.02]
}

cabinet_pose : {
    position : {
        x : 0, y : 0, z : 0
    },
    orientation : {
        x : 0, y : 0, z : 0, w : 0
    }
}
table_pose : {
    position : {
        x : 0, y : 0, z : 0
    },
    orientation : {
        x : 0, y : 0, z : 0, w : 0
    }
}

# This list is in order of priority. If it sees a drink, it will try 
# to pick this up first. Then fruits. etc. "tableware" is hard, so 
# that's close to the bottom. We will not attempt containers or cutlery.
categories_to_pick_up : [
    "drinks", 
    "fruits", 
    "food", 
    "snacks", 
    "tableware", 
    "cleaning_stuff"]