# Basic flag to wait for the parameters to be loaded in.
params_loaded: True

execute_navigation_commands: true

# For putting down objects next to others
find_placement_options : {
    # Looks for a space height m
    height : 0.3,
    # Looks for placement options radius away
    radius : 0.2,
    # Assumes the object is dims in dimension.
    dims : [0.05, 0.05, 0.2]
}