# Basic flag to wait for the parameters to be loaded in.
params_loaded: True

execute_navigation_commands: true

# For putting down objects next to others
find_placement_options : {
    # Looks for a space height m
    height : 1,
    # Looks for placement options radius away
    radius : 0.1,
    # Assumes the object is dims in dimension.
    dims : [0.05, 0.05, 0.2]
}

cabinet_pose : {
    position : {
        x : 0, y : 0, z : 0
    },
    orientation : {
        x : 0, y : 0, z : 0, w : 0
    }
}
table_pose : {
    position : {
        x : 0, y : 0, z : 0
    },
    orientation : {
        x : 0, y : 0, z : 0, w : 0
    }
}