# Basic flag to wait for the parameters to be loaded in.
params_loaded: True

execute_navigation_commands: true



use_grasping_synthesis : false
use_collision_mapping : false

# For putting down objects next to others
find_placement_options : {
    # Looks for a plane height meters below the point given. This should thus probably be like 20cm max.
    height : 0.2,
    # Looks for placement options radius away
    radius : 0.04,
    # Assumes the object is dims in dimension.
    dims : [0.05, 0.05, -0.01]
}

table_pose : {
    # Bordeaux
    position : {
        # x: 6.898829284925901, y: -0.3345450406571554, z: 0.0
        x: 7.132535664637315, y: -0.22092364986656335, z: 0.0
    },
    orientation : { 
        x: 0.0, y: 0.0, z: 0.9941701850029624, w: 0.1078222762288735
    }
    # Simulation
    # position : {
    #     x : 4.61, y : 0.308, z : 0
    # },
    # orientation : {
    #     x : 0, y : 0, z : 0.751, w : 0.66
    # }
}
cabinet_pose : {
    # Bordeaux
    position : {
        x: 6.921234442581973, y: -0.28322414645887983, z: 0.0
    },
    orientation : { 
        x: 0.0, y: 0.0, z: 0.5969085861979543, w: 0.8023092544169981
    }
    # Simulation
    # position : {
    #     x : 2.62, y : 0.36, z : 0
    # },
    # orientation : {
    #     x : 0, y : 0, z : -0.821, w : 0.571
    # }
}

# This list is in order of priority. If it sees a drink, it will try 
# to pick this up first. Then fruits. etc. "tableware" is hard, so 
# that's close to the bottom. We will not attempt containers or cutlery.
categories_to_pick_up : [
    "fruits", 
    "drinks", 
    "food", 
    "snacks", 
    "tableware", 
    "cleaning_stuff"]

class_name_filter : [
    'banana', 'bananas',
    'strawberry'
]

# There will be false positives within the vision system. However, we will count ourselves very unlucky if
# we get multiple false positives of the same field. Thus, when we query into the SOM system, we will be 
# looking for a minimum number of observations, given below. On the SOM side, this is input by simply setting
# the `num_observations` parameter within the query.
min_number_of_observations : 3

table_mast_height : 0
cabinet_mast_height : 0


# Next thing to worry about is potentially hardcoding the shelves.
use_hardcoded_shelves : true
shelves_hardcoded : {
    normal: [0,0,1],
    z_vals: [0.45,0.735,1.06,1.41,1.70],
    # Pose of the base of the shelves
    shelf_pose: {
        position : {
            x : 7.3, y : 0.86, z : 0.5
        },
        orientation : {
            x : 0, y : 0, z: 0.9956340984489936, w: 0.09334206985952051
        }
    },
    width : 0.8,
    depth : 0.27
}