# Basic flag to wait for the parameters to be loaded in.
params_loaded: True

execute_navigation_commands: True


centre_of_room_pose : {
    position : {
        x : 4.61, y : 0.308, z : 0
    },
    orientation : {
        x : 0, y : 0, z : 0.751, w : 0.66
    }
}
exit_pose : {
    position : {
        x : 2.62, y : 0.36, z : 0
    },
    orientation : {
        x : 0, y : 0, z : -0.821, w : 0.571
    }
}